# Generated by Django 5.2 on 2025-08-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sexual_preference',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('all', 'all')]),
        ),
    ]
