# Generated by Django 5.2 on 2025-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_sexual_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='swiped_left',
            field=models.ManyToManyField(related_name='swiped_left_by', to='api.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='swiped_right',
            field=models.ManyToManyField(related_name='swiped_right_by', to='api.profile'),
        ),
    ]
