# Generated by Django 5.2 on 2025-07-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_photo_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
