# Generated by Django 5.2.5 on 2025-08-22 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_swiped_left_profile_swiped_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='swiped_left',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='swiped_right',
        ),
        migrations.AddField(
            model_name='profile',
            name='left_swiped',
            field=models.ManyToManyField(blank=True, related_name='swiped_left_by', to='api.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='right_swiped',
            field=models.ManyToManyField(blank=True, related_name='swiped_right_by', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
