# Generated by Django 5.2.5 on 2025-08-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_profile_swiped_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='left_swiped',
            field=models.ManyToManyField(blank=True, related_name='left_swiped_by', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='right_swiped',
            field=models.ManyToManyField(blank=True, related_name='right_swiped_by', to='api.profile'),
        ),
    ]
