# Generated by Django 5.2 on 2025-07-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='user_profile',
            new_name='profile',
        ),
    ]
