# Generated by Django 5.2.5 on 2025-11-06 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('high_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_conversations', to='api.profile')),
                ('low_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_conversations', to='api.profile')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation'),
            preserve_default=False,
        ),
    ]
