# Generated by Django 5.2.5 on 2025-08-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_user_profile_photo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='gay'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sexual_orientation',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('both', 'both'), ('all', 'all')], default='gay'),
            preserve_default=False,
        ),
    ]
