# Generated by Django 5.2.5 on 2025-11-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_conversation_message_conversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='low_profile',
            new_name='profile1',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='high_profile',
            new_name='profile2',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_active',
        ),
        migrations.AddField(
            model_name='profile',
            name='matched',
            field=models.ManyToManyField(blank=True, to='api.profile'),
        ),
    ]
