# Generated by Django 5.2 on 2025-08-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_gender_profile_sexual_orientation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sexual_orientation',
            new_name='sexual_preference',
        ),
    ]
