# Generated by Django 5.2.5 on 2025-11-16 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='matched',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default='2025-11-16'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count1', models.PositiveSmallIntegerField(default=0)),
                ('unread_count2', models.PositiveSmallIntegerField(default=0)),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_matches', to='api.profile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_matches', to='api.profile')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='match',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='matched2',
            field=models.ManyToManyField(blank=True, through='api.Match', to='api.profile'),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
