# Generated by Django 5.2.5 on 2025-11-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_message_conversation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='matched2',
            new_name='matched',
        ),
    ]
