# Generated by Django 5.2.5 on 2025-11-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_matched2_profile_matched'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('profile1', 'profile2'), name='unique_match'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('profile1__lt', models.F('profile2'))), name='profile1_less_than_profile2'),
        ),
    ]
