# Generated by Django 5.2.5 on 2025-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_match_unique_match_match_profile1_less_than_profile2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_age_diff',
            field=models.SmallIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='min_age_diff',
            field=models.SmallIntegerField(default=-3),
            preserve_default=False,
        ),
    ]
