# Generated by Django 5.2.5 on 2025-11-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profile_max_age_diff_profile_min_age_diff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='max_age_diff',
            new_name='older_age_diff',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='min_age_diff',
            new_name='younger_age_diff',
        ),
    ]
