# Generated by Django 5.2 on 2025-11-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verification_token',
            new_name='verification_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email_verification_sent_at',
            new_name='verification_token_sent_at',
        ),
    ]
