# Generated by Django 5.2 on 2025-11-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_email_verification_token_user_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
