# Generated by Django 5.2 on 2025-11-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_password_reset_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_token_sent_at',
            new_name='email_verification_sent_at',
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
