# Generated by Django 5.2.5 on 2025-11-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_verification_token_sent_at_user_email_verification_sent_at_and_more'),
    ]

    operations = [
    ]
