# Generated by Django 5.2.5 on 2025-11-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20251123_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='old_text',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='old_bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='old_first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='old_gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='old_last_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='sexual_preference',
            new_name='old_sexual_preference',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verification_token',
            new_name='old_verification_token',
        ),
        migrations.AddField(
            model_name='user',
            name='old_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
