# Generated by Django 5.2.5 on 2025-11-23 00:01

import api.models
import secured_fields.fields
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_text_message_old_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=secured_fields.fields.EncryptedTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=secured_fields.fields.EncryptedTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=secured_fields.fields.EncryptedCharField(default='', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=secured_fields.fields.EncryptedCharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=secured_fields.fields.EncryptedCharField(default='', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sexual_preference',
            field=secured_fields.fields.EncryptedCharField(choices=[('male', 'male'), ('female', 'female'), ('all', 'all')], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='new_username',
            field=secured_fields.fields.EncryptedCharField(default='', help_text='Required. 150 chars or fewer.', max_length=150, searchable=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=api.models.EncryptedUUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=api.models.EncryptedEmailField(blank=True, max_length=254, null=True),
        ),
    ]
