# Generated by Django 5.2.5 on 2025-11-23 00:20

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_message_text_profile_bio_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='old_verification_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=api.models.EncryptedUUIDField(default=uuid.uuid4),
        ),
    ]
