# Generated by Django 5.2.5 on 2025-11-23 00:22

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_user_old_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='old_verification_token',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=api.models.EncryptedUUIDField(default=uuid.uuid4, null=True),
        ),
    ]
