# Generated by Django 5.2.5 on 2025-11-23 00:36

import api.models
import secured_fields.fields
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_user_old_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=secured_fields.fields.EncryptedCharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], searchable=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexual_preference',
            field=secured_fields.fields.EncryptedCharField(choices=[('male', 'male'), ('female', 'female'), ('all', 'all')], searchable=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=api.models.EncryptedEmailField(blank=True, max_length=254, null=True, searchable=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='new_username',
            field=secured_fields.fields.EncryptedCharField(help_text='Required. 150 chars or fewer.', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=api.models.EncryptedUUIDField(default=uuid.uuid4, null=True, searchable=True),
        ),
    ]
