# Generated by Django 5.2.5 on 2025-11-23 00:56

import secured_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_profile_gender_alter_profile_sexual_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='a@a.com', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='new_username',
            field=secured_fields.fields.EncryptedCharField(help_text='Required. 150 chars or fewer.', max_length=150, searchable=True),
        ),
    ]
