# Generated by Django 5.2.5 on 2025-11-23 00:56

import api.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_user_verification_token_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=api.models.EncryptedUUIDField(default=uuid.uuid4, null=True, searchable=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=api.models.EncryptedEmailField(blank=True, max_length=254, null=True, searchable=True),
        ),
    ]
