# Generated by Django 5.2.5 on 2025-11-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_user_verification_token_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
    ]
