# Generated by Django 5.2.5 on 2025-11-23 12:56

import api.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_user_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=api.models.EncryptedUUIDField(default=uuid.uuid4, null=True, searchable=True),
        ),
    ]
