# Generated by Django 5.2.5 on 2025-11-23 13:00

import api.models
import secured_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_user_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=api.models.EncryptedEmailField(default='john.pork@mng.ch', max_length=254, searchable=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='new_username',
            field=secured_fields.fields.EncryptedCharField(max_length=150, searchable=True),
        ),
    ]
