# Generated by Django 5.2.5 on 2025-11-23 13:41

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_user_email_alter_user_new_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='new_username',
            field=api.models.UsernameField(max_length=150, searchable=True),
        ),
    ]
