# Generated by Django 5.2.5 on 2025-11-23 13:44

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=api.models.EncryptedEmailField(max_length=254, searchable=True),
        ),
    ]
