# Generated by Django 5.2.5 on 2025-11-23 13:49

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='old_text',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='old_bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='old_first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='old_gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='old_last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='old_sexual_preference',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='old_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='old_verification_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=api.models.UsernameField(max_length=150, searchable=True),
        ),
    ]
