# Generated by Django 5.2.5 on 2025-11-23 14:01

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_message_old_text_remove_profile_old_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_email',
            field=api.models.EncryptedEmailField(blank=True, max_length=254, null=True),
        ),
    ]
