# Generated by Django 5.2.5 on 2025-11-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_user_new_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='new_email',
        ),
    ]
