# Generated by Django 5.2.5 on 2025-11-23 14:03

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_user_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_email',
            field=api.models.EncryptedEmailField(blank=True, max_length=254, null=True),
        ),
    ]
