# Generated by Django 5.2.5 on 2025-11-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_user_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='elo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='elo_games_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
