# Generated by Django 5.2.5 on 2025-11-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_profile_elo_profile_elo_games_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='elo_games_count',
            new_name='swiped_on_count',
        ),
    ]
