# Generated by Django 5.2.5 on 2025-11-25 14:42

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_rename_elo_games_count_profile_swiped_on_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=api.models.EncryptedUUIDField(default=uuid.uuid4, searchable=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['match', 'created_at'], name='api_message_match_i_e5a7b9_idx'),
        ),
    ]
