# Generated by Django 5.2.5 on 2025-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_bannedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_tos',
            field=models.BooleanField(default=False),
        ),
    ]
