# Generated by Django 5.2.5 on 2025-12-01 19:56

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_user_accepted_tos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-last_notification_at']},
        ),
        migrations.AddField(
            model_name='match',
            name='last_notification_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
    ]
