# Generated by Django 5.2.5 on 2025-12-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_match_options_match_last_notification_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['last_notification_at']},
        ),
    ]
