# Generated by Django 5.2.5 on 2025-12-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_match_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.AlterField(
            model_name='match',
            name='last_notification_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
